// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "Unittest_mset.pb.h"
// @@protoc_insertion_point(imports)

@implementation UnittestMsetRoot
static id<PBExtensionField> TestMessageSetExtension1_messageSetExtension = nil;
static id<PBExtensionField> TestMessageSetExtension2_messageSetExtension = nil;
static PBExtensionRegistry* extensionRegistry = nil;
+ (PBExtensionRegistry*) extensionRegistry {
  return extensionRegistry;
}

+ (void) initialize {
  if (self == [UnittestMsetRoot class]) {
    TestMessageSetExtension1_messageSetExtension =
      [PBConcreteExtensionField extensionWithType:PBExtensionTypeMessage
                                     extendedClass:[TestMessageSet class]
                                       fieldNumber:1545008
                                      defaultValue:[TestMessageSetExtension1 defaultInstance]
                               messageOrGroupClass:[TestMessageSetExtension1 class]
                                        isRepeated:NO
                                          isPacked:NO
                            isMessageSetWireFormat:YES];
    TestMessageSetExtension2_messageSetExtension =
      [PBConcreteExtensionField extensionWithType:PBExtensionTypeMessage
                                     extendedClass:[TestMessageSet class]
                                       fieldNumber:1547769
                                      defaultValue:[TestMessageSetExtension2 defaultInstance]
                               messageOrGroupClass:[TestMessageSetExtension2 class]
                                        isRepeated:NO
                                          isPacked:NO
                            isMessageSetWireFormat:YES];
    PBMutableExtensionRegistry* registry = [PBMutableExtensionRegistry registry];
    [self registerAllExtensions:registry];
    extensionRegistry = registry;
  }
}
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry {
  [registry addExtension:TestMessageSetExtension1_messageSetExtension];
  [registry addExtension:TestMessageSetExtension2_messageSetExtension];
}
@end

@interface TestMessageSet ()
@end

@implementation TestMessageSet

- (instancetype) init {
  if ((self = [super init])) {
  }
  return self;
}
static TestMessageSet* defaultTestMessageSetInstance = nil;
+ (void) initialize {
  if (self == [TestMessageSet class]) {
    defaultTestMessageSetInstance = [[TestMessageSet alloc] init];
  }
}
+ (instancetype) defaultInstance {
  return defaultTestMessageSetInstance;
}
- (instancetype) defaultInstance {
  return defaultTestMessageSetInstance;
}
- (BOOL) isInitialized {
  if (!self.extensionsAreInitialized) {
    return NO;
  }
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  [self writeExtensionsToCodedOutputStream:output
                                      from:4
                                        to:2147483647];
  [self.unknownFields writeAsMessageSetTo:output];
}
- (SInt32) serializedSize {
  __block SInt32 size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  size_ += [self extensionsSerializedSize];
  size_ += self.unknownFields.serializedSizeAsMessageSet;
  memoizedSerializedSize = size_;
  return size_;
}
+ (TestMessageSet*) parseFromData:(NSData*) data {
  return (TestMessageSet*)[[[TestMessageSet builder] mergeFromData:data] build];
}
+ (TestMessageSet*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (TestMessageSet*)[[[TestMessageSet builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (TestMessageSet*) parseFromInputStream:(NSInputStream*) input {
  return (TestMessageSet*)[[[TestMessageSet builder] mergeFromInputStream:input] build];
}
+ (TestMessageSet*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (TestMessageSet*)[[[TestMessageSet builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (TestMessageSet*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (TestMessageSet*)[[[TestMessageSet builder] mergeFromCodedInputStream:input] build];
}
+ (TestMessageSet*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (TestMessageSet*)[[[TestMessageSet builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (TestMessageSetBuilder*) builder {
  return [[TestMessageSetBuilder alloc] init];
}
+ (TestMessageSetBuilder*) builderWithPrototype:(TestMessageSet*) prototype {
  return [[TestMessageSet builder] mergeFrom:prototype];
}
- (TestMessageSetBuilder*) builder {
  return [TestMessageSet builder];
}
- (TestMessageSetBuilder*) toBuilder {
  return [TestMessageSet builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  [self writeExtensionDescriptionToMutableString:(NSMutableString*)output
                                            from:4
                                              to:2147483647
                                      withIndent:indent];
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (void) storeInDictionary:(NSMutableDictionary *)dictionary {
  [self.unknownFields storeInDictionary:dictionary];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[TestMessageSet class]]) {
    return NO;
  }
  TestMessageSet *otherMessage = other;
  return
      [self isEqualExtensionsInOther:otherMessage from:4 to:2147483647] &&

      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  __block NSUInteger hashCode = 7;
  hashCode = hashCode * 31 + [self hashExtensionsFrom:4 to:2147483647];
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

@interface TestMessageSetBuilder()
@property (strong) TestMessageSet* resultTestMessageSet;
@end

@implementation TestMessageSetBuilder
@synthesize resultTestMessageSet;
- (instancetype) init {
  if ((self = [super init])) {
    self.resultTestMessageSet = [[TestMessageSet alloc] init];
  }
  return self;
}
- (PBExtendableMessage*) internalGetResult {
  return resultTestMessageSet;
}
- (TestMessageSetBuilder*) clear {
  self.resultTestMessageSet = [[TestMessageSet alloc] init];
  return self;
}
- (TestMessageSetBuilder*) clone {
  return [TestMessageSet builderWithPrototype:resultTestMessageSet];
}
- (TestMessageSet*) defaultInstance {
  return [TestMessageSet defaultInstance];
}
- (TestMessageSet*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (TestMessageSet*) buildPartial {
  TestMessageSet* returnMe = resultTestMessageSet;
  self.resultTestMessageSet = nil;
  return returnMe;
}
- (TestMessageSetBuilder*) mergeFrom:(TestMessageSet*) other {
  if (other == [TestMessageSet defaultInstance]) {
    return self;
  }
  [self mergeExtensionFields:other];
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (TestMessageSetBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (TestMessageSetBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSetBuilder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    SInt32 tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
    }
  }
}
@end

@interface TestMessageSetContainer ()
@property (strong) TestMessageSet* messageSet;
@end

@implementation TestMessageSetContainer

- (BOOL) hasMessageSet {
  return !!hasMessageSet_;
}
- (void) setHasMessageSet:(BOOL) _value_ {
  hasMessageSet_ = !!_value_;
}
@synthesize messageSet;
- (instancetype) init {
  if ((self = [super init])) {
    self.messageSet = [TestMessageSet defaultInstance];
  }
  return self;
}
static TestMessageSetContainer* defaultTestMessageSetContainerInstance = nil;
+ (void) initialize {
  if (self == [TestMessageSetContainer class]) {
    defaultTestMessageSetContainerInstance = [[TestMessageSetContainer alloc] init];
  }
}
+ (instancetype) defaultInstance {
  return defaultTestMessageSetContainerInstance;
}
- (instancetype) defaultInstance {
  return defaultTestMessageSetContainerInstance;
}
- (BOOL) isInitialized {
  if (self.hasMessageSet) {
    if (!self.messageSet.isInitialized) {
      return NO;
    }
  }
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasMessageSet) {
    [output writeMessage:1 value:self.messageSet];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (SInt32) serializedSize {
  __block SInt32 size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  if (self.hasMessageSet) {
    size_ += computeMessageSize(1, self.messageSet);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (TestMessageSetContainer*) parseFromData:(NSData*) data {
  return (TestMessageSetContainer*)[[[TestMessageSetContainer builder] mergeFromData:data] build];
}
+ (TestMessageSetContainer*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (TestMessageSetContainer*)[[[TestMessageSetContainer builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (TestMessageSetContainer*) parseFromInputStream:(NSInputStream*) input {
  return (TestMessageSetContainer*)[[[TestMessageSetContainer builder] mergeFromInputStream:input] build];
}
+ (TestMessageSetContainer*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (TestMessageSetContainer*)[[[TestMessageSetContainer builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (TestMessageSetContainer*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (TestMessageSetContainer*)[[[TestMessageSetContainer builder] mergeFromCodedInputStream:input] build];
}
+ (TestMessageSetContainer*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (TestMessageSetContainer*)[[[TestMessageSetContainer builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (TestMessageSetContainerBuilder*) builder {
  return [[TestMessageSetContainerBuilder alloc] init];
}
+ (TestMessageSetContainerBuilder*) builderWithPrototype:(TestMessageSetContainer*) prototype {
  return [[TestMessageSetContainer builder] mergeFrom:prototype];
}
- (TestMessageSetContainerBuilder*) builder {
  return [TestMessageSetContainer builder];
}
- (TestMessageSetContainerBuilder*) toBuilder {
  return [TestMessageSetContainer builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasMessageSet) {
    [output appendFormat:@"%@%@ {\n", indent, @"messageSet"];
    [self.messageSet writeDescriptionTo:output
                         withIndent:[NSString stringWithFormat:@"%@  ", indent]];
    [output appendFormat:@"%@}\n", indent];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (void) storeInDictionary:(NSMutableDictionary *)dictionary {
  if (self.hasMessageSet) {
   NSMutableDictionary *messageDictionary = [NSMutableDictionary dictionary]; 
   [self.messageSet storeInDictionary:messageDictionary];
   [dictionary setObject:[NSDictionary dictionaryWithDictionary:messageDictionary] forKey:@"messageSet"];
  }
  [self.unknownFields storeInDictionary:dictionary];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[TestMessageSetContainer class]]) {
    return NO;
  }
  TestMessageSetContainer *otherMessage = other;
  return
      self.hasMessageSet == otherMessage.hasMessageSet &&
      (!self.hasMessageSet || [self.messageSet isEqual:otherMessage.messageSet]) &&
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  __block NSUInteger hashCode = 7;
  if (self.hasMessageSet) {
    hashCode = hashCode * 31 + [self.messageSet hash];
  }
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

@interface TestMessageSetContainerBuilder()
@property (strong) TestMessageSetContainer* resultTestMessageSetContainer;
@end

@implementation TestMessageSetContainerBuilder
@synthesize resultTestMessageSetContainer;
- (instancetype) init {
  if ((self = [super init])) {
    self.resultTestMessageSetContainer = [[TestMessageSetContainer alloc] init];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return resultTestMessageSetContainer;
}
- (TestMessageSetContainerBuilder*) clear {
  self.resultTestMessageSetContainer = [[TestMessageSetContainer alloc] init];
  return self;
}
- (TestMessageSetContainerBuilder*) clone {
  return [TestMessageSetContainer builderWithPrototype:resultTestMessageSetContainer];
}
- (TestMessageSetContainer*) defaultInstance {
  return [TestMessageSetContainer defaultInstance];
}
- (TestMessageSetContainer*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (TestMessageSetContainer*) buildPartial {
  TestMessageSetContainer* returnMe = resultTestMessageSetContainer;
  self.resultTestMessageSetContainer = nil;
  return returnMe;
}
- (TestMessageSetContainerBuilder*) mergeFrom:(TestMessageSetContainer*) other {
  if (other == [TestMessageSetContainer defaultInstance]) {
    return self;
  }
  if (other.hasMessageSet) {
    [self mergeMessageSet:other.messageSet];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (TestMessageSetContainerBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (TestMessageSetContainerBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSetBuilder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    SInt32 tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        TestMessageSetBuilder* subBuilder = [TestMessageSet builder];
        if (self.hasMessageSet) {
          [subBuilder mergeFrom:self.messageSet];
        }
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self setMessageSet:[subBuilder buildPartial]];
        break;
      }
    }
  }
}
- (BOOL) hasMessageSet {
  return resultTestMessageSetContainer.hasMessageSet;
}
- (TestMessageSet*) messageSet {
  return resultTestMessageSetContainer.messageSet;
}
- (TestMessageSetContainerBuilder*) setMessageSet:(TestMessageSet*) value {
  resultTestMessageSetContainer.hasMessageSet = YES;
  resultTestMessageSetContainer.messageSet = value;
  return self;
}
- (TestMessageSetContainerBuilder*) setMessageSetBuilder:(TestMessageSetBuilder*) builderForValue {
  return [self setMessageSet:[builderForValue build]];
}
- (TestMessageSetContainerBuilder*) mergeMessageSet:(TestMessageSet*) value {
  if (resultTestMessageSetContainer.hasMessageSet &&
      resultTestMessageSetContainer.messageSet != [TestMessageSet defaultInstance]) {
    resultTestMessageSetContainer.messageSet =
      [[[TestMessageSet builderWithPrototype:resultTestMessageSetContainer.messageSet] mergeFrom:value] buildPartial];
  } else {
    resultTestMessageSetContainer.messageSet = value;
  }
  resultTestMessageSetContainer.hasMessageSet = YES;
  return self;
}
- (TestMessageSetContainerBuilder*) clearMessageSet {
  resultTestMessageSetContainer.hasMessageSet = NO;
  resultTestMessageSetContainer.messageSet = [TestMessageSet defaultInstance];
  return self;
}
@end

@interface TestMessageSetExtension1 ()
@property SInt32 i;
@end

@implementation TestMessageSetExtension1

- (BOOL) hasI {
  return !!hasI_;
}
- (void) setHasI:(BOOL) _value_ {
  hasI_ = !!_value_;
}
@synthesize i;
- (instancetype) init {
  if ((self = [super init])) {
    self.i = 0;
  }
  return self;
}
+ (id<PBExtensionField>) messageSetExtension {
  return TestMessageSetExtension1_messageSetExtension;
}
static TestMessageSetExtension1* defaultTestMessageSetExtension1Instance = nil;
+ (void) initialize {
  if (self == [TestMessageSetExtension1 class]) {
    defaultTestMessageSetExtension1Instance = [[TestMessageSetExtension1 alloc] init];
  }
}
+ (instancetype) defaultInstance {
  return defaultTestMessageSetExtension1Instance;
}
- (instancetype) defaultInstance {
  return defaultTestMessageSetExtension1Instance;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasI) {
    [output writeInt32:15 value:self.i];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (SInt32) serializedSize {
  __block SInt32 size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  if (self.hasI) {
    size_ += computeInt32Size(15, self.i);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (TestMessageSetExtension1*) parseFromData:(NSData*) data {
  return (TestMessageSetExtension1*)[[[TestMessageSetExtension1 builder] mergeFromData:data] build];
}
+ (TestMessageSetExtension1*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (TestMessageSetExtension1*)[[[TestMessageSetExtension1 builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (TestMessageSetExtension1*) parseFromInputStream:(NSInputStream*) input {
  return (TestMessageSetExtension1*)[[[TestMessageSetExtension1 builder] mergeFromInputStream:input] build];
}
+ (TestMessageSetExtension1*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (TestMessageSetExtension1*)[[[TestMessageSetExtension1 builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (TestMessageSetExtension1*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (TestMessageSetExtension1*)[[[TestMessageSetExtension1 builder] mergeFromCodedInputStream:input] build];
}
+ (TestMessageSetExtension1*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (TestMessageSetExtension1*)[[[TestMessageSetExtension1 builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (TestMessageSetExtension1Builder*) builder {
  return [[TestMessageSetExtension1Builder alloc] init];
}
+ (TestMessageSetExtension1Builder*) builderWithPrototype:(TestMessageSetExtension1*) prototype {
  return [[TestMessageSetExtension1 builder] mergeFrom:prototype];
}
- (TestMessageSetExtension1Builder*) builder {
  return [TestMessageSetExtension1 builder];
}
- (TestMessageSetExtension1Builder*) toBuilder {
  return [TestMessageSetExtension1 builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasI) {
    [output appendFormat:@"%@%@: %@\n", indent, @"i", [NSNumber numberWithInteger:self.i]];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (void) storeInDictionary:(NSMutableDictionary *)dictionary {
  if (self.hasI) {
    [dictionary setObject: [NSNumber numberWithInteger:self.i] forKey: @"i"];
  }
  [self.unknownFields storeInDictionary:dictionary];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[TestMessageSetExtension1 class]]) {
    return NO;
  }
  TestMessageSetExtension1 *otherMessage = other;
  return
      self.hasI == otherMessage.hasI &&
      (!self.hasI || self.i == otherMessage.i) &&
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  __block NSUInteger hashCode = 7;
  if (self.hasI) {
    hashCode = hashCode * 31 + [[NSNumber numberWithInteger:self.i] hash];
  }
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

@interface TestMessageSetExtension1Builder()
@property (strong) TestMessageSetExtension1* resultTestMessageSetExtension1;
@end

@implementation TestMessageSetExtension1Builder
@synthesize resultTestMessageSetExtension1;
- (instancetype) init {
  if ((self = [super init])) {
    self.resultTestMessageSetExtension1 = [[TestMessageSetExtension1 alloc] init];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return resultTestMessageSetExtension1;
}
- (TestMessageSetExtension1Builder*) clear {
  self.resultTestMessageSetExtension1 = [[TestMessageSetExtension1 alloc] init];
  return self;
}
- (TestMessageSetExtension1Builder*) clone {
  return [TestMessageSetExtension1 builderWithPrototype:resultTestMessageSetExtension1];
}
- (TestMessageSetExtension1*) defaultInstance {
  return [TestMessageSetExtension1 defaultInstance];
}
- (TestMessageSetExtension1*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (TestMessageSetExtension1*) buildPartial {
  TestMessageSetExtension1* returnMe = resultTestMessageSetExtension1;
  self.resultTestMessageSetExtension1 = nil;
  return returnMe;
}
- (TestMessageSetExtension1Builder*) mergeFrom:(TestMessageSetExtension1*) other {
  if (other == [TestMessageSetExtension1 defaultInstance]) {
    return self;
  }
  if (other.hasI) {
    [self setI:other.i];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (TestMessageSetExtension1Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (TestMessageSetExtension1Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSetBuilder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    SInt32 tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 120: {
        [self setI:[input readInt32]];
        break;
      }
    }
  }
}
- (BOOL) hasI {
  return resultTestMessageSetExtension1.hasI;
}
- (SInt32) i {
  return resultTestMessageSetExtension1.i;
}
- (TestMessageSetExtension1Builder*) setI:(SInt32) value {
  resultTestMessageSetExtension1.hasI = YES;
  resultTestMessageSetExtension1.i = value;
  return self;
}
- (TestMessageSetExtension1Builder*) clearI {
  resultTestMessageSetExtension1.hasI = NO;
  resultTestMessageSetExtension1.i = 0;
  return self;
}
@end

@interface TestMessageSetExtension2 ()
@property (strong) NSString* str;
@end

@implementation TestMessageSetExtension2

- (BOOL) hasStr {
  return !!hasStr_;
}
- (void) setHasStr:(BOOL) _value_ {
  hasStr_ = !!_value_;
}
@synthesize str;
- (instancetype) init {
  if ((self = [super init])) {
    self.str = @"";
  }
  return self;
}
+ (id<PBExtensionField>) messageSetExtension {
  return TestMessageSetExtension2_messageSetExtension;
}
static TestMessageSetExtension2* defaultTestMessageSetExtension2Instance = nil;
+ (void) initialize {
  if (self == [TestMessageSetExtension2 class]) {
    defaultTestMessageSetExtension2Instance = [[TestMessageSetExtension2 alloc] init];
  }
}
+ (instancetype) defaultInstance {
  return defaultTestMessageSetExtension2Instance;
}
- (instancetype) defaultInstance {
  return defaultTestMessageSetExtension2Instance;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasStr) {
    [output writeString:25 value:self.str];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (SInt32) serializedSize {
  __block SInt32 size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  if (self.hasStr) {
    size_ += computeStringSize(25, self.str);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (TestMessageSetExtension2*) parseFromData:(NSData*) data {
  return (TestMessageSetExtension2*)[[[TestMessageSetExtension2 builder] mergeFromData:data] build];
}
+ (TestMessageSetExtension2*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (TestMessageSetExtension2*)[[[TestMessageSetExtension2 builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (TestMessageSetExtension2*) parseFromInputStream:(NSInputStream*) input {
  return (TestMessageSetExtension2*)[[[TestMessageSetExtension2 builder] mergeFromInputStream:input] build];
}
+ (TestMessageSetExtension2*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (TestMessageSetExtension2*)[[[TestMessageSetExtension2 builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (TestMessageSetExtension2*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (TestMessageSetExtension2*)[[[TestMessageSetExtension2 builder] mergeFromCodedInputStream:input] build];
}
+ (TestMessageSetExtension2*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (TestMessageSetExtension2*)[[[TestMessageSetExtension2 builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (TestMessageSetExtension2Builder*) builder {
  return [[TestMessageSetExtension2Builder alloc] init];
}
+ (TestMessageSetExtension2Builder*) builderWithPrototype:(TestMessageSetExtension2*) prototype {
  return [[TestMessageSetExtension2 builder] mergeFrom:prototype];
}
- (TestMessageSetExtension2Builder*) builder {
  return [TestMessageSetExtension2 builder];
}
- (TestMessageSetExtension2Builder*) toBuilder {
  return [TestMessageSetExtension2 builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasStr) {
    [output appendFormat:@"%@%@: %@\n", indent, @"str", self.str];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (void) storeInDictionary:(NSMutableDictionary *)dictionary {
  if (self.hasStr) {
    [dictionary setObject: self.str forKey: @"str"];
  }
  [self.unknownFields storeInDictionary:dictionary];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[TestMessageSetExtension2 class]]) {
    return NO;
  }
  TestMessageSetExtension2 *otherMessage = other;
  return
      self.hasStr == otherMessage.hasStr &&
      (!self.hasStr || [self.str isEqual:otherMessage.str]) &&
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  __block NSUInteger hashCode = 7;
  if (self.hasStr) {
    hashCode = hashCode * 31 + [self.str hash];
  }
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

@interface TestMessageSetExtension2Builder()
@property (strong) TestMessageSetExtension2* resultTestMessageSetExtension2;
@end

@implementation TestMessageSetExtension2Builder
@synthesize resultTestMessageSetExtension2;
- (instancetype) init {
  if ((self = [super init])) {
    self.resultTestMessageSetExtension2 = [[TestMessageSetExtension2 alloc] init];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return resultTestMessageSetExtension2;
}
- (TestMessageSetExtension2Builder*) clear {
  self.resultTestMessageSetExtension2 = [[TestMessageSetExtension2 alloc] init];
  return self;
}
- (TestMessageSetExtension2Builder*) clone {
  return [TestMessageSetExtension2 builderWithPrototype:resultTestMessageSetExtension2];
}
- (TestMessageSetExtension2*) defaultInstance {
  return [TestMessageSetExtension2 defaultInstance];
}
- (TestMessageSetExtension2*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (TestMessageSetExtension2*) buildPartial {
  TestMessageSetExtension2* returnMe = resultTestMessageSetExtension2;
  self.resultTestMessageSetExtension2 = nil;
  return returnMe;
}
- (TestMessageSetExtension2Builder*) mergeFrom:(TestMessageSetExtension2*) other {
  if (other == [TestMessageSetExtension2 defaultInstance]) {
    return self;
  }
  if (other.hasStr) {
    [self setStr:other.str];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (TestMessageSetExtension2Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (TestMessageSetExtension2Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSetBuilder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    SInt32 tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 202: {
        [self setStr:[input readString]];
        break;
      }
    }
  }
}
- (BOOL) hasStr {
  return resultTestMessageSetExtension2.hasStr;
}
- (NSString*) str {
  return resultTestMessageSetExtension2.str;
}
- (TestMessageSetExtension2Builder*) setStr:(NSString*) value {
  resultTestMessageSetExtension2.hasStr = YES;
  resultTestMessageSetExtension2.str = value;
  return self;
}
- (TestMessageSetExtension2Builder*) clearStr {
  resultTestMessageSetExtension2.hasStr = NO;
  resultTestMessageSetExtension2.str = @"";
  return self;
}
@end

@interface RawMessageSet ()
@property (strong) NSMutableArray * itemArray;
@end

@implementation RawMessageSet

@synthesize itemArray;
@dynamic item;
- (instancetype) init {
  if ((self = [super init])) {
  }
  return self;
}
static RawMessageSet* defaultRawMessageSetInstance = nil;
+ (void) initialize {
  if (self == [RawMessageSet class]) {
    defaultRawMessageSetInstance = [[RawMessageSet alloc] init];
  }
}
+ (instancetype) defaultInstance {
  return defaultRawMessageSetInstance;
}
- (instancetype) defaultInstance {
  return defaultRawMessageSetInstance;
}
- (NSArray *)item {
  return itemArray;
}
- (RawMessageSetItem*)itemAtIndex:(NSUInteger)index {
  return [itemArray objectAtIndex:index];
}
- (BOOL) isInitialized {
  __block BOOL isInititem = YES;
   [self.item enumerateObjectsUsingBlock:^(RawMessageSetItem *element, NSUInteger idx, BOOL *stop) {
    if (!element.isInitialized) {
      isInititem = NO;
      *stop = YES;
    }
  }];
  if (!isInititem) return isInititem;
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  [self.itemArray enumerateObjectsUsingBlock:^(RawMessageSetItem *element, NSUInteger idx, BOOL *stop) {
    [output writeGroup:1 value:element];
  }];
  [self.unknownFields writeToCodedOutputStream:output];
}
- (SInt32) serializedSize {
  __block SInt32 size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  [self.itemArray enumerateObjectsUsingBlock:^(RawMessageSetItem *element, NSUInteger idx, BOOL *stop) {
    size_ += computeGroupSize(1, element);
  }];
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (RawMessageSet*) parseFromData:(NSData*) data {
  return (RawMessageSet*)[[[RawMessageSet builder] mergeFromData:data] build];
}
+ (RawMessageSet*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (RawMessageSet*)[[[RawMessageSet builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (RawMessageSet*) parseFromInputStream:(NSInputStream*) input {
  return (RawMessageSet*)[[[RawMessageSet builder] mergeFromInputStream:input] build];
}
+ (RawMessageSet*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (RawMessageSet*)[[[RawMessageSet builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (RawMessageSet*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (RawMessageSet*)[[[RawMessageSet builder] mergeFromCodedInputStream:input] build];
}
+ (RawMessageSet*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (RawMessageSet*)[[[RawMessageSet builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (RawMessageSetBuilder*) builder {
  return [[RawMessageSetBuilder alloc] init];
}
+ (RawMessageSetBuilder*) builderWithPrototype:(RawMessageSet*) prototype {
  return [[RawMessageSet builder] mergeFrom:prototype];
}
- (RawMessageSetBuilder*) builder {
  return [RawMessageSet builder];
}
- (RawMessageSetBuilder*) toBuilder {
  return [RawMessageSet builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  [self.itemArray enumerateObjectsUsingBlock:^(RawMessageSetItem *element, NSUInteger idx, BOOL *stop) {
    [output appendFormat:@"%@%@ {\n", indent, @"item"];
    [element writeDescriptionTo:output
                     withIndent:[NSString stringWithFormat:@"%@  ", indent]];
    [output appendFormat:@"%@}\n", indent];
  }];
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (void) storeInDictionary:(NSMutableDictionary *)dictionary {
  for (RawMessageSetItem* element in self.itemArray) {
    NSMutableDictionary *elementDictionary = [NSMutableDictionary dictionary];
    [element storeInDictionary:elementDictionary];
    [dictionary setObject:[NSDictionary dictionaryWithDictionary:elementDictionary] forKey:@"item"];
  }
  [self.unknownFields storeInDictionary:dictionary];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[RawMessageSet class]]) {
    return NO;
  }
  RawMessageSet *otherMessage = other;
  return
      [self.itemArray isEqualToArray:otherMessage.itemArray] &&
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  __block NSUInteger hashCode = 7;
  [self.itemArray enumerateObjectsUsingBlock:^(RawMessageSetItem *element, NSUInteger idx, BOOL *stop) {
    hashCode = hashCode * 31 + [element hash];
  }];
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

@interface RawMessageSetItem ()
@property SInt32 typeId;
@property (strong) NSData* message;
@end

@implementation RawMessageSetItem

- (BOOL) hasTypeId {
  return !!hasTypeId_;
}
- (void) setHasTypeId:(BOOL) _value_ {
  hasTypeId_ = !!_value_;
}
@synthesize typeId;
- (BOOL) hasMessage {
  return !!hasMessage_;
}
- (void) setHasMessage:(BOOL) _value_ {
  hasMessage_ = !!_value_;
}
@synthesize message;
- (instancetype) init {
  if ((self = [super init])) {
    self.typeId = 0;
    self.message = [NSData data];
  }
  return self;
}
static RawMessageSetItem* defaultRawMessageSetItemInstance = nil;
+ (void) initialize {
  if (self == [RawMessageSetItem class]) {
    defaultRawMessageSetItemInstance = [[RawMessageSetItem alloc] init];
  }
}
+ (instancetype) defaultInstance {
  return defaultRawMessageSetItemInstance;
}
- (instancetype) defaultInstance {
  return defaultRawMessageSetItemInstance;
}
- (BOOL) isInitialized {
  if (!self.hasTypeId) {
    return NO;
  }
  if (!self.hasMessage) {
    return NO;
  }
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasTypeId) {
    [output writeInt32:2 value:self.typeId];
  }
  if (self.hasMessage) {
    [output writeData:3 value:self.message];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (SInt32) serializedSize {
  __block SInt32 size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  if (self.hasTypeId) {
    size_ += computeInt32Size(2, self.typeId);
  }
  if (self.hasMessage) {
    size_ += computeDataSize(3, self.message);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (RawMessageSetItem*) parseFromData:(NSData*) data {
  return (RawMessageSetItem*)[[[RawMessageSetItem builder] mergeFromData:data] build];
}
+ (RawMessageSetItem*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (RawMessageSetItem*)[[[RawMessageSetItem builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (RawMessageSetItem*) parseFromInputStream:(NSInputStream*) input {
  return (RawMessageSetItem*)[[[RawMessageSetItem builder] mergeFromInputStream:input] build];
}
+ (RawMessageSetItem*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (RawMessageSetItem*)[[[RawMessageSetItem builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (RawMessageSetItem*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (RawMessageSetItem*)[[[RawMessageSetItem builder] mergeFromCodedInputStream:input] build];
}
+ (RawMessageSetItem*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (RawMessageSetItem*)[[[RawMessageSetItem builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (RawMessageSetItemBuilder*) builder {
  return [[RawMessageSetItemBuilder alloc] init];
}
+ (RawMessageSetItemBuilder*) builderWithPrototype:(RawMessageSetItem*) prototype {
  return [[RawMessageSetItem builder] mergeFrom:prototype];
}
- (RawMessageSetItemBuilder*) builder {
  return [RawMessageSetItem builder];
}
- (RawMessageSetItemBuilder*) toBuilder {
  return [RawMessageSetItem builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasTypeId) {
    [output appendFormat:@"%@%@: %@\n", indent, @"typeId", [NSNumber numberWithInteger:self.typeId]];
  }
  if (self.hasMessage) {
    [output appendFormat:@"%@%@: %@\n", indent, @"message", self.message];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (void) storeInDictionary:(NSMutableDictionary *)dictionary {
  if (self.hasTypeId) {
    [dictionary setObject: [NSNumber numberWithInteger:self.typeId] forKey: @"typeId"];
  }
  if (self.hasMessage) {
    [dictionary setObject: self.message forKey: @"message"];
  }
  [self.unknownFields storeInDictionary:dictionary];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[RawMessageSetItem class]]) {
    return NO;
  }
  RawMessageSetItem *otherMessage = other;
  return
      self.hasTypeId == otherMessage.hasTypeId &&
      (!self.hasTypeId || self.typeId == otherMessage.typeId) &&
      self.hasMessage == otherMessage.hasMessage &&
      (!self.hasMessage || [self.message isEqual:otherMessage.message]) &&
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  __block NSUInteger hashCode = 7;
  if (self.hasTypeId) {
    hashCode = hashCode * 31 + [[NSNumber numberWithInteger:self.typeId] hash];
  }
  if (self.hasMessage) {
    hashCode = hashCode * 31 + [self.message hash];
  }
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

@interface RawMessageSetItemBuilder()
@property (strong) RawMessageSetItem* resultItem;
@end

@implementation RawMessageSetItemBuilder
@synthesize resultItem;
- (instancetype) init {
  if ((self = [super init])) {
    self.resultItem = [[RawMessageSetItem alloc] init];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return resultItem;
}
- (RawMessageSetItemBuilder*) clear {
  self.resultItem = [[RawMessageSetItem alloc] init];
  return self;
}
- (RawMessageSetItemBuilder*) clone {
  return [RawMessageSetItem builderWithPrototype:resultItem];
}
- (RawMessageSetItem*) defaultInstance {
  return [RawMessageSetItem defaultInstance];
}
- (RawMessageSetItem*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (RawMessageSetItem*) buildPartial {
  RawMessageSetItem* returnMe = resultItem;
  self.resultItem = nil;
  return returnMe;
}
- (RawMessageSetItemBuilder*) mergeFrom:(RawMessageSetItem*) other {
  if (other == [RawMessageSetItem defaultInstance]) {
    return self;
  }
  if (other.hasTypeId) {
    [self setTypeId:other.typeId];
  }
  if (other.hasMessage) {
    [self setMessage:other.message];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (RawMessageSetItemBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (RawMessageSetItemBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSetBuilder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    SInt32 tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 16: {
        [self setTypeId:[input readInt32]];
        break;
      }
      case 26: {
        [self setMessage:[input readData]];
        break;
      }
    }
  }
}
- (BOOL) hasTypeId {
  return resultItem.hasTypeId;
}
- (SInt32) typeId {
  return resultItem.typeId;
}
- (RawMessageSetItemBuilder*) setTypeId:(SInt32) value {
  resultItem.hasTypeId = YES;
  resultItem.typeId = value;
  return self;
}
- (RawMessageSetItemBuilder*) clearTypeId {
  resultItem.hasTypeId = NO;
  resultItem.typeId = 0;
  return self;
}
- (BOOL) hasMessage {
  return resultItem.hasMessage;
}
- (NSData*) message {
  return resultItem.message;
}
- (RawMessageSetItemBuilder*) setMessage:(NSData*) value {
  resultItem.hasMessage = YES;
  resultItem.message = value;
  return self;
}
- (RawMessageSetItemBuilder*) clearMessage {
  resultItem.hasMessage = NO;
  resultItem.message = [NSData data];
  return self;
}
@end

@interface RawMessageSetBuilder()
@property (strong) RawMessageSet* resultRawMessageSet;
@end

@implementation RawMessageSetBuilder
@synthesize resultRawMessageSet;
- (instancetype) init {
  if ((self = [super init])) {
    self.resultRawMessageSet = [[RawMessageSet alloc] init];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return resultRawMessageSet;
}
- (RawMessageSetBuilder*) clear {
  self.resultRawMessageSet = [[RawMessageSet alloc] init];
  return self;
}
- (RawMessageSetBuilder*) clone {
  return [RawMessageSet builderWithPrototype:resultRawMessageSet];
}
- (RawMessageSet*) defaultInstance {
  return [RawMessageSet defaultInstance];
}
- (RawMessageSet*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (RawMessageSet*) buildPartial {
  RawMessageSet* returnMe = resultRawMessageSet;
  self.resultRawMessageSet = nil;
  return returnMe;
}
- (RawMessageSetBuilder*) mergeFrom:(RawMessageSet*) other {
  if (other == [RawMessageSet defaultInstance]) {
    return self;
  }
  if (other.itemArray.count > 0) {
    if (resultRawMessageSet.itemArray == nil) {
      resultRawMessageSet.itemArray = [[NSMutableArray alloc] initWithArray:other.itemArray];
    } else {
      [resultRawMessageSet.itemArray addObjectsFromArray:other.itemArray];
    }
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (RawMessageSetBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (RawMessageSetBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSetBuilder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    SInt32 tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 11: {
        RawMessageSetItemBuilder* subBuilder = [RawMessageSetItem builder];
        [input readGroup:1 builder:subBuilder extensionRegistry:extensionRegistry];
        [self addItem:[subBuilder buildPartial]];
        break;
      }
    }
  }
}
- (NSMutableArray *)item {
  return resultRawMessageSet.itemArray;
}
- (RawMessageSetItem*)itemAtIndex:(NSUInteger)index {
  return [resultRawMessageSet itemAtIndex:index];
}
- (RawMessageSetBuilder *)addItem:(RawMessageSetItem*)value {
  if (resultRawMessageSet.itemArray == nil) {
    resultRawMessageSet.itemArray = [[NSMutableArray alloc]init];
  }
  [resultRawMessageSet.itemArray addObject:value];
  return self;
}
- (RawMessageSetBuilder *)setItemArray:(NSArray *)array {
  resultRawMessageSet.itemArray = [[NSMutableArray alloc]initWithArray:array];
  return self;
}
- (RawMessageSetBuilder *)clearItem {
  resultRawMessageSet.itemArray = nil;
  return self;
}
@end


// @@protoc_insertion_point(global_scope)
