// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

#import "Unittest_import_public_lite.pb.h"
// @@protoc_insertion_point(imports)

@class ImportMessageLite;
@class ImportMessageLiteBuilder;
@class PublicImportMessageLite;
@class PublicImportMessageLiteBuilder;


typedef NS_ENUM(SInt32, ImportEnumLite) {
  ImportEnumLiteImportLiteFoo = 7,
  ImportEnumLiteImportLiteBar = 8,
  ImportEnumLiteImportLiteBaz = 9,
};

BOOL ImportEnumLiteIsValidValue(ImportEnumLite value);
NSString *NSStringFromImportEnumLite(ImportEnumLite value);


@interface UnittestImportLiteRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

#define ImportMessageLite_d @"d"
@interface ImportMessageLite : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasD_:1;
  SInt32 d;
}
- (BOOL) hasD;
@property (readonly) SInt32 d;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ImportMessageLiteBuilder*) builder;
+ (ImportMessageLiteBuilder*) builder;
+ (ImportMessageLiteBuilder*) builderWithPrototype:(ImportMessageLite*) prototype;
- (ImportMessageLiteBuilder*) toBuilder;

+ (ImportMessageLite*) parseFromData:(NSData*) data;
+ (ImportMessageLite*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ImportMessageLite*) parseFromInputStream:(NSInputStream*) input;
+ (ImportMessageLite*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ImportMessageLite*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ImportMessageLite*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ImportMessageLiteBuilder : PBGeneratedMessageBuilder {
@private
  ImportMessageLite* resultImportMessageLite;
}

- (ImportMessageLite*) defaultInstance;

- (ImportMessageLiteBuilder*) clear;
- (ImportMessageLiteBuilder*) clone;

- (ImportMessageLite*) build;
- (ImportMessageLite*) buildPartial;

- (ImportMessageLiteBuilder*) mergeFrom:(ImportMessageLite*) other;
- (ImportMessageLiteBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ImportMessageLiteBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasD;
- (SInt32) d;
- (ImportMessageLiteBuilder*) setD:(SInt32) value;
- (ImportMessageLiteBuilder*) clearD;
@end


// @@protoc_insertion_point(global_scope)
