// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

// @@protoc_insertion_point(imports)

@class Body;
@class BodyBuilder;
@class Header;
@class HeaderBuilder;
@class O2Msg;
@class O2MsgBuilder;



@interface O2Root : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

#define Header_type @"type"
#define Header_length @"length"
@interface Header : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasType_:1;
  BOOL hasLength_:1;
  UInt32 type;
  UInt32 length;
}
- (BOOL) hasType;
- (BOOL) hasLength;
@property (readonly) UInt32 type;
@property (readonly) UInt32 length;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (HeaderBuilder*) builder;
+ (HeaderBuilder*) builder;
+ (HeaderBuilder*) builderWithPrototype:(Header*) prototype;
- (HeaderBuilder*) toBuilder;

+ (Header*) parseFromData:(NSData*) data;
+ (Header*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Header*) parseFromInputStream:(NSInputStream*) input;
+ (Header*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Header*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Header*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface HeaderBuilder : PBGeneratedMessageBuilder {
@private
  Header* resultHeader;
}

- (Header*) defaultInstance;

- (HeaderBuilder*) clear;
- (HeaderBuilder*) clone;

- (Header*) build;
- (Header*) buildPartial;

- (HeaderBuilder*) mergeFrom:(Header*) other;
- (HeaderBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (HeaderBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasType;
- (UInt32) type;
- (HeaderBuilder*) setType:(UInt32) value;
- (HeaderBuilder*) clearType;

- (BOOL) hasLength;
- (UInt32) length;
- (HeaderBuilder*) setLength:(UInt32) value;
- (HeaderBuilder*) clearLength;
@end

#define Body_fromUserId @"fromUserId"
#define Body_toUserId @"toUserId"
#define Body_content @"content"
#define Body_buffer @"buffer"
#define Body_second @"second"
@interface Body : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasSecond_:1;
  BOOL hasContent_:1;
  BOOL hasBuffer_:1;
  BOOL hasFromUserId_:1;
  BOOL hasToUserId_:1;
  SInt32 second;
  NSString* content;
  NSData* buffer;
  UInt32 fromUserId;
  UInt32 toUserId;
}
- (BOOL) hasFromUserId;
- (BOOL) hasToUserId;
- (BOOL) hasContent;
- (BOOL) hasBuffer;
- (BOOL) hasSecond;
@property (readonly) UInt32 fromUserId;
@property (readonly) UInt32 toUserId;
@property (readonly, strong) NSString* content;
@property (readonly, strong) NSData* buffer;
@property (readonly) SInt32 second;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (BodyBuilder*) builder;
+ (BodyBuilder*) builder;
+ (BodyBuilder*) builderWithPrototype:(Body*) prototype;
- (BodyBuilder*) toBuilder;

+ (Body*) parseFromData:(NSData*) data;
+ (Body*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Body*) parseFromInputStream:(NSInputStream*) input;
+ (Body*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Body*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Body*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface BodyBuilder : PBGeneratedMessageBuilder {
@private
  Body* resultBody;
}

- (Body*) defaultInstance;

- (BodyBuilder*) clear;
- (BodyBuilder*) clone;

- (Body*) build;
- (Body*) buildPartial;

- (BodyBuilder*) mergeFrom:(Body*) other;
- (BodyBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (BodyBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasFromUserId;
- (UInt32) fromUserId;
- (BodyBuilder*) setFromUserId:(UInt32) value;
- (BodyBuilder*) clearFromUserId;

- (BOOL) hasToUserId;
- (UInt32) toUserId;
- (BodyBuilder*) setToUserId:(UInt32) value;
- (BodyBuilder*) clearToUserId;

- (BOOL) hasContent;
- (NSString*) content;
- (BodyBuilder*) setContent:(NSString*) value;
- (BodyBuilder*) clearContent;

- (BOOL) hasBuffer;
- (NSData*) buffer;
- (BodyBuilder*) setBuffer:(NSData*) value;
- (BodyBuilder*) clearBuffer;

- (BOOL) hasSecond;
- (SInt32) second;
- (BodyBuilder*) setSecond:(SInt32) value;
- (BodyBuilder*) clearSecond;
@end

#define O2Msg_header @"header"
#define O2Msg_body @"body"
@interface O2Msg : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasHeader_:1;
  BOOL hasBody_:1;
  Header* header;
  Body* body;
}
- (BOOL) hasHeader;
- (BOOL) hasBody;
@property (readonly, strong) Header* header;
@property (readonly, strong) Body* body;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (O2MsgBuilder*) builder;
+ (O2MsgBuilder*) builder;
+ (O2MsgBuilder*) builderWithPrototype:(O2Msg*) prototype;
- (O2MsgBuilder*) toBuilder;

+ (O2Msg*) parseFromData:(NSData*) data;
+ (O2Msg*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (O2Msg*) parseFromInputStream:(NSInputStream*) input;
+ (O2Msg*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (O2Msg*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (O2Msg*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface O2MsgBuilder : PBGeneratedMessageBuilder {
@private
  O2Msg* resultO2Msg;
}

- (O2Msg*) defaultInstance;

- (O2MsgBuilder*) clear;
- (O2MsgBuilder*) clone;

- (O2Msg*) build;
- (O2Msg*) buildPartial;

- (O2MsgBuilder*) mergeFrom:(O2Msg*) other;
- (O2MsgBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (O2MsgBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasHeader;
- (Header*) header;
- (O2MsgBuilder*) setHeader:(Header*) value;
- (O2MsgBuilder*) setHeaderBuilder:(HeaderBuilder*) builderForValue;
- (O2MsgBuilder*) mergeHeader:(Header*) value;
- (O2MsgBuilder*) clearHeader;

- (BOOL) hasBody;
- (Body*) body;
- (O2MsgBuilder*) setBody:(Body*) value;
- (O2MsgBuilder*) setBodyBuilder:(BodyBuilder*) builderForValue;
- (O2MsgBuilder*) mergeBody:(Body*) value;
- (O2MsgBuilder*) clearBody;
@end


// @@protoc_insertion_point(global_scope)
