// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtocolMessage.proto

package com.seaofheart.app.chat.protocol;

public final class ProtocolMessage {
  private ProtocolMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code com.seaofheart.app.chat.protocol.TYPE}
   *
   * <pre>
   *option java_outer_classname = "PersonProbuf"; 
   * </pre>
   */
  public enum TYPE
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>TXT = 0;</code>
     */
    TXT(0, 0),
    /**
     * <code>CMD = 1;</code>
     */
    CMD(1, 1),
    /**
     * <code>LOCATION = 2;</code>
     */
    LOCATION(2, 2),
    /**
     * <code>IMAGE = 3;</code>
     */
    IMAGE(3, 3),
    /**
     * <code>VIDEO = 4;</code>
     */
    VIDEO(4, 4),
    /**
     * <code>VOICE = 5;</code>
     */
    VOICE(5, 5),
    /**
     * <code>FILE = 6;</code>
     */
    FILE(6, 6),
    UNRECOGNIZED(-1, -1),
    ;

    /**
     * <code>TXT = 0;</code>
     */
    public static final int TXT_VALUE = 0;
    /**
     * <code>CMD = 1;</code>
     */
    public static final int CMD_VALUE = 1;
    /**
     * <code>LOCATION = 2;</code>
     */
    public static final int LOCATION_VALUE = 2;
    /**
     * <code>IMAGE = 3;</code>
     */
    public static final int IMAGE_VALUE = 3;
    /**
     * <code>VIDEO = 4;</code>
     */
    public static final int VIDEO_VALUE = 4;
    /**
     * <code>VOICE = 5;</code>
     */
    public static final int VOICE_VALUE = 5;
    /**
     * <code>FILE = 6;</code>
     */
    public static final int FILE_VALUE = 6;


    public final int getNumber() {
      if (index == -1) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    public static TYPE valueOf(int value) {
      switch (value) {
        case 0: return TXT;
        case 1: return CMD;
        case 2: return LOCATION;
        case 3: return IMAGE;
        case 4: return VIDEO;
        case 5: return VOICE;
        case 6: return FILE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<TYPE>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        TYPE> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<TYPE>() {
            public TYPE findValueByNumber(int number) {
              return TYPE.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.seaofheart.app.chat.protocol.ProtocolMessage.getDescriptor().getEnumTypes().get(0);
    }

    private static final TYPE[] VALUES = values();

    public static TYPE valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private TYPE(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.seaofheart.app.chat.protocol.TYPE)
  }

  /**
   * Protobuf enum {@code com.seaofheart.app.chat.protocol.CHAT_TYPE}
   */
  public enum CHAT_TYPE
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>CHAT_SINGLE = 0;</code>
     */
    CHAT_SINGLE(0, 0),
    /**
     * <code>CHAT_GROUP = 1;</code>
     */
    CHAT_GROUP(1, 1),
    /**
     * <code>CHAT_ROOM = 2;</code>
     */
    CHAT_ROOM(2, 2),
    UNRECOGNIZED(-1, -1),
    ;

    /**
     * <code>CHAT_SINGLE = 0;</code>
     */
    public static final int CHAT_SINGLE_VALUE = 0;
    /**
     * <code>CHAT_GROUP = 1;</code>
     */
    public static final int CHAT_GROUP_VALUE = 1;
    /**
     * <code>CHAT_ROOM = 2;</code>
     */
    public static final int CHAT_ROOM_VALUE = 2;


    public final int getNumber() {
      if (index == -1) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    public static CHAT_TYPE valueOf(int value) {
      switch (value) {
        case 0: return CHAT_SINGLE;
        case 1: return CHAT_GROUP;
        case 2: return CHAT_ROOM;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<CHAT_TYPE>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        CHAT_TYPE> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<CHAT_TYPE>() {
            public CHAT_TYPE findValueByNumber(int number) {
              return CHAT_TYPE.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.seaofheart.app.chat.protocol.ProtocolMessage.getDescriptor().getEnumTypes().get(1);
    }

    private static final CHAT_TYPE[] VALUES = values();

    public static CHAT_TYPE valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private CHAT_TYPE(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.seaofheart.app.chat.protocol.CHAT_TYPE)
  }

  /**
   * Protobuf enum {@code com.seaofheart.app.chat.protocol.DIRECT}
   */
  public enum DIRECT
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>SEND = 0;</code>
     */
    SEND(0, 0),
    /**
     * <code>RECEIVE = 1;</code>
     */
    RECEIVE(1, 1),
    UNRECOGNIZED(-1, -1),
    ;

    /**
     * <code>SEND = 0;</code>
     */
    public static final int SEND_VALUE = 0;
    /**
     * <code>RECEIVE = 1;</code>
     */
    public static final int RECEIVE_VALUE = 1;


    public final int getNumber() {
      if (index == -1) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    public static DIRECT valueOf(int value) {
      switch (value) {
        case 0: return SEND;
        case 1: return RECEIVE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<DIRECT>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        DIRECT> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<DIRECT>() {
            public DIRECT findValueByNumber(int number) {
              return DIRECT.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.seaofheart.app.chat.protocol.ProtocolMessage.getDescriptor().getEnumTypes().get(2);
    }

    private static final DIRECT[] VALUES = values();

    public static DIRECT valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private DIRECT(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.seaofheart.app.chat.protocol.DIRECT)
  }

  /**
   * Protobuf enum {@code com.seaofheart.app.chat.protocol.STATUS}
   */
  public enum STATUS
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>SUCCESS = 0;</code>
     */
    SUCCESS(0, 0),
    /**
     * <code>FAIL = 1;</code>
     */
    FAIL(1, 1),
    /**
     * <code>INPROGRESS = 2;</code>
     */
    INPROGRESS(2, 2),
    /**
     * <code>CREATE = 3;</code>
     */
    CREATE(3, 3),
    UNRECOGNIZED(-1, -1),
    ;

    /**
     * <code>SUCCESS = 0;</code>
     */
    public static final int SUCCESS_VALUE = 0;
    /**
     * <code>FAIL = 1;</code>
     */
    public static final int FAIL_VALUE = 1;
    /**
     * <code>INPROGRESS = 2;</code>
     */
    public static final int INPROGRESS_VALUE = 2;
    /**
     * <code>CREATE = 3;</code>
     */
    public static final int CREATE_VALUE = 3;


    public final int getNumber() {
      if (index == -1) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    public static STATUS valueOf(int value) {
      switch (value) {
        case 0: return SUCCESS;
        case 1: return FAIL;
        case 2: return INPROGRESS;
        case 3: return CREATE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<STATUS>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        STATUS> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<STATUS>() {
            public STATUS findValueByNumber(int number) {
              return STATUS.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.seaofheart.app.chat.protocol.ProtocolMessage.getDescriptor().getEnumTypes().get(3);
    }

    private static final STATUS[] VALUES = values();

    public static STATUS valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private STATUS(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.seaofheart.app.chat.protocol.STATUS)
  }

  public interface MTMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.seaofheart.app.chat.protocol.MTMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string msg_id = 1;</code>
     *
     * <pre>
     *Header header = 1;
     *uint32 msg_id = 1;
     * </pre>
     */
    java.lang.String getMsgId();
    /**
     * <code>optional string msg_id = 1;</code>
     *
     * <pre>
     *Header header = 1;
     *uint32 msg_id = 1;
     * </pre>
     */
    com.google.protobuf.ByteString
        getMsgIdBytes();

    /**
     * <code>optional .com.seaofheart.app.chat.protocol.TYPE type = 2;</code>
     */
    int getTypeValue();
    /**
     * <code>optional .com.seaofheart.app.chat.protocol.TYPE type = 2;</code>
     */
    com.seaofheart.app.chat.protocol.ProtocolMessage.TYPE getType();

    /**
     * <code>optional .com.seaofheart.app.chat.protocol.STATUS status = 3;</code>
     */
    int getStatusValue();
    /**
     * <code>optional .com.seaofheart.app.chat.protocol.STATUS status = 3;</code>
     */
    com.seaofheart.app.chat.protocol.ProtocolMessage.STATUS getStatus();

    /**
     * <code>optional .com.seaofheart.app.chat.protocol.DIRECT direct = 4;</code>
     */
    int getDirectValue();
    /**
     * <code>optional .com.seaofheart.app.chat.protocol.DIRECT direct = 4;</code>
     */
    com.seaofheart.app.chat.protocol.ProtocolMessage.DIRECT getDirect();

    /**
     * <code>optional .com.seaofheart.app.chat.protocol.CHAT_TYPE chat_type = 5;</code>
     */
    int getChatTypeValue();
    /**
     * <code>optional .com.seaofheart.app.chat.protocol.CHAT_TYPE chat_type = 5;</code>
     */
    com.seaofheart.app.chat.protocol.ProtocolMessage.CHAT_TYPE getChatType();

    /**
     * <code>optional string from = 6;</code>
     *
     * <pre>
     *Body body = 5;
     *uint32 from = 6; // 发送方用户id
     *uint32 to = 7; // 接收方用户id
     * </pre>
     */
    java.lang.String getFrom();
    /**
     * <code>optional string from = 6;</code>
     *
     * <pre>
     *Body body = 5;
     *uint32 from = 6; // 发送方用户id
     *uint32 to = 7; // 接收方用户id
     * </pre>
     */
    com.google.protobuf.ByteString
        getFromBytes();

    /**
     * <code>optional string to = 7;</code>
     *
     * <pre>
     * 接收方用户id
     * </pre>
     */
    java.lang.String getTo();
    /**
     * <code>optional string to = 7;</code>
     *
     * <pre>
     * 接收方用户id
     * </pre>
     */
    com.google.protobuf.ByteString
        getToBytes();

    /**
     * <code>optional string content = 8;</code>
     *
     * <pre>
     * 如果发的是文字，则文字内容放到这个字段，buffer字段等不使用。
     * </pre>
     */
    java.lang.String getContent();
    /**
     * <code>optional string content = 8;</code>
     *
     * <pre>
     * 如果发的是文字，则文字内容放到这个字段，buffer字段等不使用。
     * </pre>
     */
    com.google.protobuf.ByteString
        getContentBytes();

    /**
     * <code>optional bytes buffer = 9;</code>
     *
     * <pre>
     * 如果发的是二进制数据，则放到这个字段，content字段不使用。
     * </pre>
     */
    com.google.protobuf.ByteString getBuffer();

    /**
     * <code>optional int32 second = 10;</code>
     *
     * <pre>
     * 如果发的是语言，则这个字段表示语音时长，s为单位。
     * </pre>
     */
    int getSecond();

    /**
     * <code>optional uint32 timeline = 11;</code>
     *
     * <pre>
     *时间戳
     * </pre>
     */
    int getTimeline();
  }
  /**
   * Protobuf type {@code com.seaofheart.app.chat.protocol.MTMessage}
   *
   * <pre>
   *message Header {
   *TYPE type = 1;
   *uint32 length = 2;
   *}
   *message Body {
   *uint32 from = 1; // 发送方用户id
   *uint32 to = 2; // 接收方用户id
   *string content = 3; // 如果发的是文字，则文字内容放到这个字段，buffer字段等不使用。
   *bytes buffer = 4; // 如果发的是二进制数据，则放到这个字段，content字段不使用。
   *int32 second = 5; // 如果发的是语言，则这个字段表示语音时长，s为单位。
   *}
   * </pre>
   */
  public  static final class MTMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.seaofheart.app.chat.protocol.MTMessage)
      MTMessageOrBuilder {
    // Use MTMessage.newBuilder() to construct.
    private MTMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private MTMessage() {
      msgId_ = "";
      type_ = 0;
      status_ = 0;
      direct_ = 0;
      chatType_ = 0;
      from_ = "";
      to_ = "";
      content_ = "";
      buffer_ = com.google.protobuf.ByteString.EMPTY;
      second_ = 0;
      timeline_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private MTMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              msgId_ = s;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              status_ = rawValue;
              break;
            }
            case 32: {
              int rawValue = input.readEnum();

              direct_ = rawValue;
              break;
            }
            case 40: {
              int rawValue = input.readEnum();

              chatType_ = rawValue;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              from_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              to_ = s;
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();

              content_ = s;
              break;
            }
            case 74: {

              buffer_ = input.readBytes();
              break;
            }
            case 80: {

              second_ = input.readInt32();
              break;
            }
            case 88: {

              timeline_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.seaofheart.app.chat.protocol.ProtocolMessage.internal_static_com_seaofheart_app_chat_protocol_MTMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.seaofheart.app.chat.protocol.ProtocolMessage.internal_static_com_seaofheart_app_chat_protocol_MTMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.seaofheart.app.chat.protocol.ProtocolMessage.MTMessage.class, com.seaofheart.app.chat.protocol.ProtocolMessage.MTMessage.Builder.class);
    }

    public static final int MSG_ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object msgId_;
    /**
     * <code>optional string msg_id = 1;</code>
     *
     * <pre>
     *Header header = 1;
     *uint32 msg_id = 1;
     * </pre>
     */
    public java.lang.String getMsgId() {
      java.lang.Object ref = msgId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        msgId_ = s;
        return s;
      }
    }
    /**
     * <code>optional string msg_id = 1;</code>
     *
     * <pre>
     *Header header = 1;
     *uint32 msg_id = 1;
     * </pre>
     */
    public com.google.protobuf.ByteString
        getMsgIdBytes() {
      java.lang.Object ref = msgId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msgId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private int type_;
    /**
     * <code>optional .com.seaofheart.app.chat.protocol.TYPE type = 2;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>optional .com.seaofheart.app.chat.protocol.TYPE type = 2;</code>
     */
    public com.seaofheart.app.chat.protocol.ProtocolMessage.TYPE getType() {
      com.seaofheart.app.chat.protocol.ProtocolMessage.TYPE result = com.seaofheart.app.chat.protocol.ProtocolMessage.TYPE.valueOf(type_);
      return result == null ? com.seaofheart.app.chat.protocol.ProtocolMessage.TYPE.UNRECOGNIZED : result;
    }

    public static final int STATUS_FIELD_NUMBER = 3;
    private int status_;
    /**
     * <code>optional .com.seaofheart.app.chat.protocol.STATUS status = 3;</code>
     */
    public int getStatusValue() {
      return status_;
    }
    /**
     * <code>optional .com.seaofheart.app.chat.protocol.STATUS status = 3;</code>
     */
    public com.seaofheart.app.chat.protocol.ProtocolMessage.STATUS getStatus() {
      com.seaofheart.app.chat.protocol.ProtocolMessage.STATUS result = com.seaofheart.app.chat.protocol.ProtocolMessage.STATUS.valueOf(status_);
      return result == null ? com.seaofheart.app.chat.protocol.ProtocolMessage.STATUS.UNRECOGNIZED : result;
    }

    public static final int DIRECT_FIELD_NUMBER = 4;
    private int direct_;
    /**
     * <code>optional .com.seaofheart.app.chat.protocol.DIRECT direct = 4;</code>
     */
    public int getDirectValue() {
      return direct_;
    }
    /**
     * <code>optional .com.seaofheart.app.chat.protocol.DIRECT direct = 4;</code>
     */
    public com.seaofheart.app.chat.protocol.ProtocolMessage.DIRECT getDirect() {
      com.seaofheart.app.chat.protocol.ProtocolMessage.DIRECT result = com.seaofheart.app.chat.protocol.ProtocolMessage.DIRECT.valueOf(direct_);
      return result == null ? com.seaofheart.app.chat.protocol.ProtocolMessage.DIRECT.UNRECOGNIZED : result;
    }

    public static final int CHAT_TYPE_FIELD_NUMBER = 5;
    private int chatType_;
    /**
     * <code>optional .com.seaofheart.app.chat.protocol.CHAT_TYPE chat_type = 5;</code>
     */
    public int getChatTypeValue() {
      return chatType_;
    }
    /**
     * <code>optional .com.seaofheart.app.chat.protocol.CHAT_TYPE chat_type = 5;</code>
     */
    public com.seaofheart.app.chat.protocol.ProtocolMessage.CHAT_TYPE getChatType() {
      com.seaofheart.app.chat.protocol.ProtocolMessage.CHAT_TYPE result = com.seaofheart.app.chat.protocol.ProtocolMessage.CHAT_TYPE.valueOf(chatType_);
      return result == null ? com.seaofheart.app.chat.protocol.ProtocolMessage.CHAT_TYPE.UNRECOGNIZED : result;
    }

    public static final int FROM_FIELD_NUMBER = 6;
    private volatile java.lang.Object from_;
    /**
     * <code>optional string from = 6;</code>
     *
     * <pre>
     *Body body = 5;
     *uint32 from = 6; // 发送方用户id
     *uint32 to = 7; // 接收方用户id
     * </pre>
     */
    public java.lang.String getFrom() {
      java.lang.Object ref = from_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        from_ = s;
        return s;
      }
    }
    /**
     * <code>optional string from = 6;</code>
     *
     * <pre>
     *Body body = 5;
     *uint32 from = 6; // 发送方用户id
     *uint32 to = 7; // 接收方用户id
     * </pre>
     */
    public com.google.protobuf.ByteString
        getFromBytes() {
      java.lang.Object ref = from_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        from_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TO_FIELD_NUMBER = 7;
    private volatile java.lang.Object to_;
    /**
     * <code>optional string to = 7;</code>
     *
     * <pre>
     * 接收方用户id
     * </pre>
     */
    public java.lang.String getTo() {
      java.lang.Object ref = to_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        to_ = s;
        return s;
      }
    }
    /**
     * <code>optional string to = 7;</code>
     *
     * <pre>
     * 接收方用户id
     * </pre>
     */
    public com.google.protobuf.ByteString
        getToBytes() {
      java.lang.Object ref = to_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        to_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONTENT_FIELD_NUMBER = 8;
    private volatile java.lang.Object content_;
    /**
     * <code>optional string content = 8;</code>
     *
     * <pre>
     * 如果发的是文字，则文字内容放到这个字段，buffer字段等不使用。
     * </pre>
     */
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        content_ = s;
        return s;
      }
    }
    /**
     * <code>optional string content = 8;</code>
     *
     * <pre>
     * 如果发的是文字，则文字内容放到这个字段，buffer字段等不使用。
     * </pre>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BUFFER_FIELD_NUMBER = 9;
    private com.google.protobuf.ByteString buffer_;
    /**
     * <code>optional bytes buffer = 9;</code>
     *
     * <pre>
     * 如果发的是二进制数据，则放到这个字段，content字段不使用。
     * </pre>
     */
    public com.google.protobuf.ByteString getBuffer() {
      return buffer_;
    }

    public static final int SECOND_FIELD_NUMBER = 10;
    private int second_;
    /**
     * <code>optional int32 second = 10;</code>
     *
     * <pre>
     * 如果发的是语言，则这个字段表示语音时长，s为单位。
     * </pre>
     */
    public int getSecond() {
      return second_;
    }

    public static final int TIMELINE_FIELD_NUMBER = 11;
    private int timeline_;
    /**
     * <code>optional uint32 timeline = 11;</code>
     *
     * <pre>
     *时间戳
     * </pre>
     */
    public int getTimeline() {
      return timeline_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getMsgIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, msgId_);
      }
      if (type_ != com.seaofheart.app.chat.protocol.ProtocolMessage.TYPE.TXT.getNumber()) {
        output.writeEnum(2, type_);
      }
      if (status_ != com.seaofheart.app.chat.protocol.ProtocolMessage.STATUS.SUCCESS.getNumber()) {
        output.writeEnum(3, status_);
      }
      if (direct_ != com.seaofheart.app.chat.protocol.ProtocolMessage.DIRECT.SEND.getNumber()) {
        output.writeEnum(4, direct_);
      }
      if (chatType_ != com.seaofheart.app.chat.protocol.ProtocolMessage.CHAT_TYPE.CHAT_SINGLE.getNumber()) {
        output.writeEnum(5, chatType_);
      }
      if (!getFromBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 6, from_);
      }
      if (!getToBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 7, to_);
      }
      if (!getContentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 8, content_);
      }
      if (!buffer_.isEmpty()) {
        output.writeBytes(9, buffer_);
      }
      if (second_ != 0) {
        output.writeInt32(10, second_);
      }
      if (timeline_ != 0) {
        output.writeUInt32(11, timeline_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getMsgIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, msgId_);
      }
      if (type_ != com.seaofheart.app.chat.protocol.ProtocolMessage.TYPE.TXT.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, type_);
      }
      if (status_ != com.seaofheart.app.chat.protocol.ProtocolMessage.STATUS.SUCCESS.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, status_);
      }
      if (direct_ != com.seaofheart.app.chat.protocol.ProtocolMessage.DIRECT.SEND.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, direct_);
      }
      if (chatType_ != com.seaofheart.app.chat.protocol.ProtocolMessage.CHAT_TYPE.CHAT_SINGLE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, chatType_);
      }
      if (!getFromBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(6, from_);
      }
      if (!getToBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(7, to_);
      }
      if (!getContentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(8, content_);
      }
      if (!buffer_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, buffer_);
      }
      if (second_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(10, second_);
      }
      if (timeline_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(11, timeline_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.seaofheart.app.chat.protocol.ProtocolMessage.MTMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.seaofheart.app.chat.protocol.ProtocolMessage.MTMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.seaofheart.app.chat.protocol.ProtocolMessage.MTMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.seaofheart.app.chat.protocol.ProtocolMessage.MTMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.seaofheart.app.chat.protocol.ProtocolMessage.MTMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.seaofheart.app.chat.protocol.ProtocolMessage.MTMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.seaofheart.app.chat.protocol.ProtocolMessage.MTMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.seaofheart.app.chat.protocol.ProtocolMessage.MTMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.seaofheart.app.chat.protocol.ProtocolMessage.MTMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.seaofheart.app.chat.protocol.ProtocolMessage.MTMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.seaofheart.app.chat.protocol.ProtocolMessage.MTMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.seaofheart.app.chat.protocol.MTMessage}
     *
     * <pre>
     *message Header {
     *TYPE type = 1;
     *uint32 length = 2;
     *}
     *message Body {
     *uint32 from = 1; // 发送方用户id
     *uint32 to = 2; // 接收方用户id
     *string content = 3; // 如果发的是文字，则文字内容放到这个字段，buffer字段等不使用。
     *bytes buffer = 4; // 如果发的是二进制数据，则放到这个字段，content字段不使用。
     *int32 second = 5; // 如果发的是语言，则这个字段表示语音时长，s为单位。
     *}
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.seaofheart.app.chat.protocol.MTMessage)
        com.seaofheart.app.chat.protocol.ProtocolMessage.MTMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.seaofheart.app.chat.protocol.ProtocolMessage.internal_static_com_seaofheart_app_chat_protocol_MTMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.seaofheart.app.chat.protocol.ProtocolMessage.internal_static_com_seaofheart_app_chat_protocol_MTMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.seaofheart.app.chat.protocol.ProtocolMessage.MTMessage.class, com.seaofheart.app.chat.protocol.ProtocolMessage.MTMessage.Builder.class);
      }

      // Construct using com.seaofheart.app.chat.protocol.ProtocolMessage.MTMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        msgId_ = "";

        type_ = 0;

        status_ = 0;

        direct_ = 0;

        chatType_ = 0;

        from_ = "";

        to_ = "";

        content_ = "";

        buffer_ = com.google.protobuf.ByteString.EMPTY;

        second_ = 0;

        timeline_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.seaofheart.app.chat.protocol.ProtocolMessage.internal_static_com_seaofheart_app_chat_protocol_MTMessage_descriptor;
      }

      public com.seaofheart.app.chat.protocol.ProtocolMessage.MTMessage getDefaultInstanceForType() {
        return com.seaofheart.app.chat.protocol.ProtocolMessage.MTMessage.getDefaultInstance();
      }

      public com.seaofheart.app.chat.protocol.ProtocolMessage.MTMessage build() {
        com.seaofheart.app.chat.protocol.ProtocolMessage.MTMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.seaofheart.app.chat.protocol.ProtocolMessage.MTMessage buildPartial() {
        com.seaofheart.app.chat.protocol.ProtocolMessage.MTMessage result = new com.seaofheart.app.chat.protocol.ProtocolMessage.MTMessage(this);
        result.msgId_ = msgId_;
        result.type_ = type_;
        result.status_ = status_;
        result.direct_ = direct_;
        result.chatType_ = chatType_;
        result.from_ = from_;
        result.to_ = to_;
        result.content_ = content_;
        result.buffer_ = buffer_;
        result.second_ = second_;
        result.timeline_ = timeline_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.seaofheart.app.chat.protocol.ProtocolMessage.MTMessage) {
          return mergeFrom((com.seaofheart.app.chat.protocol.ProtocolMessage.MTMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.seaofheart.app.chat.protocol.ProtocolMessage.MTMessage other) {
        if (other == com.seaofheart.app.chat.protocol.ProtocolMessage.MTMessage.getDefaultInstance()) return this;
        if (!other.getMsgId().isEmpty()) {
          msgId_ = other.msgId_;
          onChanged();
        }
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (other.status_ != 0) {
          setStatusValue(other.getStatusValue());
        }
        if (other.direct_ != 0) {
          setDirectValue(other.getDirectValue());
        }
        if (other.chatType_ != 0) {
          setChatTypeValue(other.getChatTypeValue());
        }
        if (!other.getFrom().isEmpty()) {
          from_ = other.from_;
          onChanged();
        }
        if (!other.getTo().isEmpty()) {
          to_ = other.to_;
          onChanged();
        }
        if (!other.getContent().isEmpty()) {
          content_ = other.content_;
          onChanged();
        }
        if (other.getBuffer() != com.google.protobuf.ByteString.EMPTY) {
          setBuffer(other.getBuffer());
        }
        if (other.getSecond() != 0) {
          setSecond(other.getSecond());
        }
        if (other.getTimeline() != 0) {
          setTimeline(other.getTimeline());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.seaofheart.app.chat.protocol.ProtocolMessage.MTMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.seaofheart.app.chat.protocol.ProtocolMessage.MTMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object msgId_ = "";
      /**
       * <code>optional string msg_id = 1;</code>
       *
       * <pre>
       *Header header = 1;
       *uint32 msg_id = 1;
       * </pre>
       */
      public java.lang.String getMsgId() {
        java.lang.Object ref = msgId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          msgId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string msg_id = 1;</code>
       *
       * <pre>
       *Header header = 1;
       *uint32 msg_id = 1;
       * </pre>
       */
      public com.google.protobuf.ByteString
          getMsgIdBytes() {
        java.lang.Object ref = msgId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msgId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string msg_id = 1;</code>
       *
       * <pre>
       *Header header = 1;
       *uint32 msg_id = 1;
       * </pre>
       */
      public Builder setMsgId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        msgId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string msg_id = 1;</code>
       *
       * <pre>
       *Header header = 1;
       *uint32 msg_id = 1;
       * </pre>
       */
      public Builder clearMsgId() {
        
        msgId_ = getDefaultInstance().getMsgId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string msg_id = 1;</code>
       *
       * <pre>
       *Header header = 1;
       *uint32 msg_id = 1;
       * </pre>
       */
      public Builder setMsgIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        msgId_ = value;
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <code>optional .com.seaofheart.app.chat.protocol.TYPE type = 2;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <code>optional .com.seaofheart.app.chat.protocol.TYPE type = 2;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .com.seaofheart.app.chat.protocol.TYPE type = 2;</code>
       */
      public com.seaofheart.app.chat.protocol.ProtocolMessage.TYPE getType() {
        com.seaofheart.app.chat.protocol.ProtocolMessage.TYPE result = com.seaofheart.app.chat.protocol.ProtocolMessage.TYPE.valueOf(type_);
        return result == null ? com.seaofheart.app.chat.protocol.ProtocolMessage.TYPE.UNRECOGNIZED : result;
      }
      /**
       * <code>optional .com.seaofheart.app.chat.protocol.TYPE type = 2;</code>
       */
      public Builder setType(com.seaofheart.app.chat.protocol.ProtocolMessage.TYPE value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .com.seaofheart.app.chat.protocol.TYPE type = 2;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private int status_ = 0;
      /**
       * <code>optional .com.seaofheart.app.chat.protocol.STATUS status = 3;</code>
       */
      public int getStatusValue() {
        return status_;
      }
      /**
       * <code>optional .com.seaofheart.app.chat.protocol.STATUS status = 3;</code>
       */
      public Builder setStatusValue(int value) {
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .com.seaofheart.app.chat.protocol.STATUS status = 3;</code>
       */
      public com.seaofheart.app.chat.protocol.ProtocolMessage.STATUS getStatus() {
        com.seaofheart.app.chat.protocol.ProtocolMessage.STATUS result = com.seaofheart.app.chat.protocol.ProtocolMessage.STATUS.valueOf(status_);
        return result == null ? com.seaofheart.app.chat.protocol.ProtocolMessage.STATUS.UNRECOGNIZED : result;
      }
      /**
       * <code>optional .com.seaofheart.app.chat.protocol.STATUS status = 3;</code>
       */
      public Builder setStatus(com.seaofheart.app.chat.protocol.ProtocolMessage.STATUS value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        status_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .com.seaofheart.app.chat.protocol.STATUS status = 3;</code>
       */
      public Builder clearStatus() {
        
        status_ = 0;
        onChanged();
        return this;
      }

      private int direct_ = 0;
      /**
       * <code>optional .com.seaofheart.app.chat.protocol.DIRECT direct = 4;</code>
       */
      public int getDirectValue() {
        return direct_;
      }
      /**
       * <code>optional .com.seaofheart.app.chat.protocol.DIRECT direct = 4;</code>
       */
      public Builder setDirectValue(int value) {
        direct_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .com.seaofheart.app.chat.protocol.DIRECT direct = 4;</code>
       */
      public com.seaofheart.app.chat.protocol.ProtocolMessage.DIRECT getDirect() {
        com.seaofheart.app.chat.protocol.ProtocolMessage.DIRECT result = com.seaofheart.app.chat.protocol.ProtocolMessage.DIRECT.valueOf(direct_);
        return result == null ? com.seaofheart.app.chat.protocol.ProtocolMessage.DIRECT.UNRECOGNIZED : result;
      }
      /**
       * <code>optional .com.seaofheart.app.chat.protocol.DIRECT direct = 4;</code>
       */
      public Builder setDirect(com.seaofheart.app.chat.protocol.ProtocolMessage.DIRECT value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        direct_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .com.seaofheart.app.chat.protocol.DIRECT direct = 4;</code>
       */
      public Builder clearDirect() {
        
        direct_ = 0;
        onChanged();
        return this;
      }

      private int chatType_ = 0;
      /**
       * <code>optional .com.seaofheart.app.chat.protocol.CHAT_TYPE chat_type = 5;</code>
       */
      public int getChatTypeValue() {
        return chatType_;
      }
      /**
       * <code>optional .com.seaofheart.app.chat.protocol.CHAT_TYPE chat_type = 5;</code>
       */
      public Builder setChatTypeValue(int value) {
        chatType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .com.seaofheart.app.chat.protocol.CHAT_TYPE chat_type = 5;</code>
       */
      public com.seaofheart.app.chat.protocol.ProtocolMessage.CHAT_TYPE getChatType() {
        com.seaofheart.app.chat.protocol.ProtocolMessage.CHAT_TYPE result = com.seaofheart.app.chat.protocol.ProtocolMessage.CHAT_TYPE.valueOf(chatType_);
        return result == null ? com.seaofheart.app.chat.protocol.ProtocolMessage.CHAT_TYPE.UNRECOGNIZED : result;
      }
      /**
       * <code>optional .com.seaofheart.app.chat.protocol.CHAT_TYPE chat_type = 5;</code>
       */
      public Builder setChatType(com.seaofheart.app.chat.protocol.ProtocolMessage.CHAT_TYPE value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        chatType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .com.seaofheart.app.chat.protocol.CHAT_TYPE chat_type = 5;</code>
       */
      public Builder clearChatType() {
        
        chatType_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object from_ = "";
      /**
       * <code>optional string from = 6;</code>
       *
       * <pre>
       *Body body = 5;
       *uint32 from = 6; // 发送方用户id
       *uint32 to = 7; // 接收方用户id
       * </pre>
       */
      public java.lang.String getFrom() {
        java.lang.Object ref = from_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          from_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string from = 6;</code>
       *
       * <pre>
       *Body body = 5;
       *uint32 from = 6; // 发送方用户id
       *uint32 to = 7; // 接收方用户id
       * </pre>
       */
      public com.google.protobuf.ByteString
          getFromBytes() {
        java.lang.Object ref = from_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          from_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string from = 6;</code>
       *
       * <pre>
       *Body body = 5;
       *uint32 from = 6; // 发送方用户id
       *uint32 to = 7; // 接收方用户id
       * </pre>
       */
      public Builder setFrom(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        from_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string from = 6;</code>
       *
       * <pre>
       *Body body = 5;
       *uint32 from = 6; // 发送方用户id
       *uint32 to = 7; // 接收方用户id
       * </pre>
       */
      public Builder clearFrom() {
        
        from_ = getDefaultInstance().getFrom();
        onChanged();
        return this;
      }
      /**
       * <code>optional string from = 6;</code>
       *
       * <pre>
       *Body body = 5;
       *uint32 from = 6; // 发送方用户id
       *uint32 to = 7; // 接收方用户id
       * </pre>
       */
      public Builder setFromBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        from_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object to_ = "";
      /**
       * <code>optional string to = 7;</code>
       *
       * <pre>
       * 接收方用户id
       * </pre>
       */
      public java.lang.String getTo() {
        java.lang.Object ref = to_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          to_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string to = 7;</code>
       *
       * <pre>
       * 接收方用户id
       * </pre>
       */
      public com.google.protobuf.ByteString
          getToBytes() {
        java.lang.Object ref = to_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          to_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string to = 7;</code>
       *
       * <pre>
       * 接收方用户id
       * </pre>
       */
      public Builder setTo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        to_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string to = 7;</code>
       *
       * <pre>
       * 接收方用户id
       * </pre>
       */
      public Builder clearTo() {
        
        to_ = getDefaultInstance().getTo();
        onChanged();
        return this;
      }
      /**
       * <code>optional string to = 7;</code>
       *
       * <pre>
       * 接收方用户id
       * </pre>
       */
      public Builder setToBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        to_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object content_ = "";
      /**
       * <code>optional string content = 8;</code>
       *
       * <pre>
       * 如果发的是文字，则文字内容放到这个字段，buffer字段等不使用。
       * </pre>
       */
      public java.lang.String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string content = 8;</code>
       *
       * <pre>
       * 如果发的是文字，则文字内容放到这个字段，buffer字段等不使用。
       * </pre>
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        java.lang.Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string content = 8;</code>
       *
       * <pre>
       * 如果发的是文字，则文字内容放到这个字段，buffer字段等不使用。
       * </pre>
       */
      public Builder setContent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string content = 8;</code>
       *
       * <pre>
       * 如果发的是文字，则文字内容放到这个字段，buffer字段等不使用。
       * </pre>
       */
      public Builder clearContent() {
        
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <code>optional string content = 8;</code>
       *
       * <pre>
       * 如果发的是文字，则文字内容放到这个字段，buffer字段等不使用。
       * </pre>
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        content_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString buffer_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes buffer = 9;</code>
       *
       * <pre>
       * 如果发的是二进制数据，则放到这个字段，content字段不使用。
       * </pre>
       */
      public com.google.protobuf.ByteString getBuffer() {
        return buffer_;
      }
      /**
       * <code>optional bytes buffer = 9;</code>
       *
       * <pre>
       * 如果发的是二进制数据，则放到这个字段，content字段不使用。
       * </pre>
       */
      public Builder setBuffer(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        buffer_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes buffer = 9;</code>
       *
       * <pre>
       * 如果发的是二进制数据，则放到这个字段，content字段不使用。
       * </pre>
       */
      public Builder clearBuffer() {
        
        buffer_ = getDefaultInstance().getBuffer();
        onChanged();
        return this;
      }

      private int second_ ;
      /**
       * <code>optional int32 second = 10;</code>
       *
       * <pre>
       * 如果发的是语言，则这个字段表示语音时长，s为单位。
       * </pre>
       */
      public int getSecond() {
        return second_;
      }
      /**
       * <code>optional int32 second = 10;</code>
       *
       * <pre>
       * 如果发的是语言，则这个字段表示语音时长，s为单位。
       * </pre>
       */
      public Builder setSecond(int value) {
        
        second_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 second = 10;</code>
       *
       * <pre>
       * 如果发的是语言，则这个字段表示语音时长，s为单位。
       * </pre>
       */
      public Builder clearSecond() {
        
        second_ = 0;
        onChanged();
        return this;
      }

      private int timeline_ ;
      /**
       * <code>optional uint32 timeline = 11;</code>
       *
       * <pre>
       *时间戳
       * </pre>
       */
      public int getTimeline() {
        return timeline_;
      }
      /**
       * <code>optional uint32 timeline = 11;</code>
       *
       * <pre>
       *时间戳
       * </pre>
       */
      public Builder setTimeline(int value) {
        
        timeline_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 timeline = 11;</code>
       *
       * <pre>
       *时间戳
       * </pre>
       */
      public Builder clearTimeline() {
        
        timeline_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.seaofheart.app.chat.protocol.MTMessage)
    }

    // @@protoc_insertion_point(class_scope:com.seaofheart.app.chat.protocol.MTMessage)
    private static final com.seaofheart.app.chat.protocol.ProtocolMessage.MTMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.seaofheart.app.chat.protocol.ProtocolMessage.MTMessage();
    }

    public static com.seaofheart.app.chat.protocol.ProtocolMessage.MTMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MTMessage>
        PARSER = new com.google.protobuf.AbstractParser<MTMessage>() {
      public MTMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new MTMessage(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<MTMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MTMessage> getParserForType() {
      return PARSER;
    }

    public com.seaofheart.app.chat.protocol.ProtocolMessage.MTMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_seaofheart_app_chat_protocol_MTMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_seaofheart_app_chat_protocol_MTMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025ProtocolMessage.proto\022 com.seaofheart." +
      "app.chat.protocol\"\342\002\n\tMTMessage\022\016\n\006msg_i" +
      "d\030\001 \001(\t\0224\n\004type\030\002 \001(\0162&.com.seaofheart.a" +
      "pp.chat.protocol.TYPE\0228\n\006status\030\003 \001(\0162(." +
      "com.seaofheart.app.chat.protocol.STATUS\022" +
      "8\n\006direct\030\004 \001(\0162(.com.seaofheart.app.cha" +
      "t.protocol.DIRECT\022>\n\tchat_type\030\005 \001(\0162+.c" +
      "om.seaofheart.app.chat.protocol.CHAT_TYP" +
      "E\022\014\n\004from\030\006 \001(\t\022\n\n\002to\030\007 \001(\t\022\017\n\007content\030\010" +
      " \001(\t\022\016\n\006buffer\030\t \001(\014\022\016\n\006second\030\n \001(\005\022\020\n\010",
      "timeline\030\013 \001(\r*Q\n\004TYPE\022\007\n\003TXT\020\000\022\007\n\003CMD\020\001" +
      "\022\014\n\010LOCATION\020\002\022\t\n\005IMAGE\020\003\022\t\n\005VIDEO\020\004\022\t\n\005" +
      "VOICE\020\005\022\010\n\004FILE\020\006*;\n\tCHAT_TYPE\022\017\n\013CHAT_S" +
      "INGLE\020\000\022\016\n\nCHAT_GROUP\020\001\022\r\n\tCHAT_ROOM\020\002*\037" +
      "\n\006DIRECT\022\010\n\004SEND\020\000\022\013\n\007RECEIVE\020\001*;\n\006STATU" +
      "S\022\013\n\007SUCCESS\020\000\022\010\n\004FAIL\020\001\022\016\n\nINPROGRESS\020\002" +
      "\022\n\n\006CREATE\020\003b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_seaofheart_app_chat_protocol_MTMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_seaofheart_app_chat_protocol_MTMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_seaofheart_app_chat_protocol_MTMessage_descriptor,
        new java.lang.String[] { "MsgId", "Type", "Status", "Direct", "ChatType", "From", "To", "Content", "Buffer", "Second", "Timeline", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
